<?php

use Drupal\Core\Field\BaseFieldDefinition;

function commerce_store_hierarchy_entity_base_field_info_alter(&$fields, \Drupal\Core\Entity\EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'commerce_store') {

    $fields['weight'] = BaseFieldDefinition::create('integer')
      ->setLabel(t('Weight'))
      ->setDescription(t('The weight of the store.'))
      ->setReadOnly(FALSE)
      ->setSetting('unsigned', FALSE)
      ->setName('weight')
      ->setDefaultValue(0)
      ->setTargetEntityTypeId('commerce_store');

    $fields['depth'] = BaseFieldDefinition::create('integer')
      ->setLabel(t('Depth'))
      ->setDescription(t('The depth of the store.'))
      ->setReadOnly(FALSE)
      ->setSetting('unsigned', TRUE)
      ->setName('depth')
      ->setDefaultValue(0)
      ->setTargetEntityTypeId('commerce_store');

    $fields['parent'] = BaseFieldDefinition::create('entity_reference')
      ->setLabel(t('Store Parents'))
      ->setDescription(t('The parents of this store.'))
      ->setSetting('target_type', 'commerce_store')
      ->setCardinality(BaseFieldDefinition::CARDINALITY_UNLIMITED)
      ->setTargetEntityTypeId('commerce_store')
      ->setDisplayOptions('form', [
        'type' => 'entity_reference_autocomplete',
        'weight' => 50,
      ])
      ->setName('parent');

  }
}
